100.00000 ^D1_Feed @!
100.00000 ^D2_Feed @!
100.00000 ^D3_Feed @!
100.00000 ^D4_Feed @!
100.00000 ^D5_Feed @!
100.00000 ^D6_Feed @!
500.00000 ^D7_Feed @!
500.00000 ^D8_Feed @!
8.0000000 ^F1_pulses @!
8.0000000 ^F2_pulses @!
8.0000000 ^F4_pulses @!
\ ""DOWNLOAD_COMPRESSION_OFF
*D1txt $INN
file:a,C:\Users\Digester\Documents\Digester1.txt
*D2txt $INN
file:a,C:\Users\Digester\Documents\Digester2.txt
*D3txt $INN
file:a,C:\Users\Digester\Documents\Digester3.txt
